name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version number"
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version
        shell: pwsh
        run: |
          $FilePath = "/PleasePwsh/PleasePwsh.psd1"
          $VersionRegex = "(ModuleVersion\s*=\s*)'\d+(\.\d+){0,2}'"
          (Get-Content $FilePath) -replace $VersionRegex, '$1''${{ github.event.inputs.version }}''' | Out-File $FilePath

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          signoff: true
